### ISSUE TITLE
jekyll update

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries-incubator/docker-introduction#145] opened 2021-09-30 13:59 UTC
for jekyll exercise, `jekyll/jekyll:pages` didn't work for me. The `4` tag did though.

**Comment by sstevens2** [comment] 2021-10-05 18:13
Hmm...the pages tagged image worked for me.  Should we look into what failed with yours?

**Comment by dme26** [comment] 2021-11-23 10:58
I tried using the `pages` tag on a (relatively) clean Docker environment and this worked for me too. I'll leave this issue open for now, though, as the cause of our inconsistent views may itself lead to improvements in the lesson even if the original container usage problem has been resolved. I might close #154 for now, though.

**Comment by aturner-epcc** [comment] 2024-08-16 08:39
With the switch to Carpentries Workbench this issue is now defunct so I will close it now.

**Closed** 2024-08-16 13:34 UTC
